
--19. Khoa nào (mã khoa, tên khoa) được thành lập sớm nhất. 
SELECT TOP 1 WITH TIES k.MAKHOA, k.TENKHOA 
FROM KHOA k 
ORDER BY k.NGTLAP 
-- 20. Có bao nhiêu giáo viên có học hàm là “GS” hoặc “PGS”. 
SELECT COUNT(*) 'So Luong'
FROM GIAOVIEN g 
WHERE g.HOCHAM IN ('GS', 'PGS')

-- Cau 21 --
SELECT MAKHOA, HOCVI, COUNT(*) AS 'So Luong'
FROM GIAOVIEN
GROUP BY MAKHOA, HOCVI;


-- Cau 22
SELECT k.MAMH, k.KQUA, COUNT(*) AS 'Ket Qua'
FROM KETQUATHI k 
GROUP BY k.MAMH, k.KQUA 
ORDER BY k.MAMH
select * from GIANGDAY
-- Cau 23 --
SELECT g.MAGV, g.HOTEN 
FROM GIAOVIEN g 
JOIN LOP l ON g.MAGV = l.MAGVCN 
JOIN GIANGDAY g2 ON g2.MALOP = l.MALOP AND g2.MAGV = g.MAGV;

-- Cau 24 --
SELECT TOP 1 h.HO + ' ' + h.TEN AS 'HO TEN'
FROM HOCVIEN h
JOIN LOP l ON h.MALOP = l.MALOP
WHERE h.MAHV = l.TRGLOP
ORDER BY l.SISO DESC;


-- Cau 25 --
SELECT h.HO + ' ' + h.TEN AS 'Họ tên trưởng lớp thi không đạt quá 3 môn'
FROM HOCVIEN h
JOIN LOP l ON h.MAHV = l.TRGLOP
JOIN KETQUATHI k ON h.MAHV = k.MAHV
WHERE k.KQUA = 'Khong Dat'
GROUP BY h.MAHV, h.HO, h.TEN
HAVING COUNT(DISTINCT k.MAMH) > 3;


-- Cau 26 --
SELECT TOP 1 WITH TIES h.MAHV, h.HO  + ' ' + h.TEN 'Ho va Ten'
FROM HOCVIEN h
JOIN KETQUATHI k 
ON h.MAHV = k.MAHV 
WHERE k.DIEM >= 9
GROUP BY h.MAHV, h.HO, h.TEN 
ORDER BY COUNT(*) DESC

-- Cau 27 --
SELECT MALOP, MAHV, HOTEN
FROM
(
	SELECT h.MALOP, h.MAHV, (Ho + ' ' + Ten) HOTEN, COUNT(*) SOLUONGDIEM, RANK() OVER (PARTITION BY MALOP ORDER BY COUNT(*) DESC) AS XEPHANG
	FROM HOCVIEN h, KETQUATHI k 
	WHERE h.MAHV = k.MAHV AND k.DIEM >= 9
	GROUP BY h.MALOP, h.MAHV, h.HO, h.TEN
) AS A
WHERE A.XEPHANG = 1

-- Cau 28 --
SELECT g.MAGV, COUNT(DISTINCT MAMH) 'So Mon Hoc', COUNT(DISTINCT MALOP) 'So Lop'
FROM GIANGDAY g 
GROUP BY g.MAGV 

-- Cau 29 --
SELECT A.HOCKY, A.NAM, A.MAGV, g.HOTEN 
FROM GIAOVIEN g,
(
	SELECT g2.HOCKY , g2.NAM, g2.MAGV, RANK() OVER (PARTITION BY g2.HOCKY, g2.NAM ORDER BY COUNT(*) DESC) AS XEPHANG
	FROM GIANGDAY g2 
	GROUP BY g2.HOCKY, g2.NAM, g2.MAGV
) AS A
WHERE A.MAGV = g.MAGV AND XEPHANG = 1
ORDER BY a.NAM, a.HOCKY

-- Cau 30 --
SELECT TOP 1 WITH TIES m.MAMH, m.TENMH
FROM MONHOC m
JOIN KETQUATHI k 
ON m.MAMH = k.MAMH 
WHERE k.LANTHI = 1 AND k.KQUA = 'Khong Dat'
GROUP BY m.MAMH, m.TENMH 
ORDER BY COUNT(*) DESC


-- Cau 31 --
SELECT DISTINCT h.MAHV, HO + ' ' + TEN 'Ho va Ten'
FROM HOCVIEN h 
JOIN KETQUATHI k 
ON h.MAHV = k.MAHV 
WHERE NOT EXISTS (
	SELECT *
	FROM KETQUATHI k2 
	WHERE k2.MAHV =h.MAHV AND k2.LANTHI = 1 AND k2.KQUA = 'Khong Dat'
)

-- Cau 32 --
SELECT DISTINCT h.MAHV, HO + ' ' + TEN 'Ho va Ten'
FROM HOCVIEN h 
JOIN KETQUATHI k 
ON h.MAHV = k.MAHV 
WHERE NOT EXISTS (
	SELECT *
	FROM KETQUATHI k2 
	WHERE k2.MAHV =h.MAHV AND k2.KQUA = 'Khong Dat'
		AND k2.LANTHI = (SELECT MAX(k3.LANTHI) FROM KETQUATHI k3 WHERE k3.MAHV = h.MAHV GROUP BY k3.MAHV)
)

-- Cau 33 --
SELECT h.MAHV , h.HO + ' ' + h.TEN 'Ho va Ten'
FROM HOCVIEN h 
WHERE NOT EXISTS
(
	SELECT *
	FROM MONHOC m 
	WHERE NOT EXISTS
	(
		SELECT *
		FROM KETQUATHI k 
		WHERE
			k.MaMH = m.MaMH
			AND k.MaHV = h.MaHV
			AND k.LANTHI = 1 AND k.KQUA = 'Dat'
	)
)

-- Cau 34 --
SELECT h.MAHV , h.HO + ' ' + h.TEN 'Ho va Ten'
FROM HOCVIEN h 
WHERE NOT EXISTS
(
	SELECT *
	FROM MONHOC m 
	WHERE NOT EXISTS
	(
		SELECT *
		FROM KETQUATHI k 
		WHERE
			k.MaMH = m.MaMH
			AND k.MaHV = h.MaHV
			AND k.LANTHI = (SELECT MAX(k3.LANTHI) FROM KETQUATHI k3 WHERE k3.MAHV = h.MAHV GROUP BY k3.MAHV)
			AND k.KQUA = 'Dat'
	)
)

-- Cau 35 --
SELECT MAMH, MAHV, HOTEN
FROM (
    SELECT k.MAMH, h.MAHV, h.HO + ' ' + h.TEN AS HOTEN, 
           RANK() OVER (PARTITION BY k.MAMH ORDER BY MAX(k.DIEM) DESC) AS XepHang
    FROM HOCVIEN h
    JOIN KETQUATHI k ON h.MAHV = k.MAHV
    WHERE k.LANTHI = (
        SELECT MAX(k2.LANTHI)
        FROM KETQUATHI k2
        WHERE k2.MAHV = h.MAHV AND k2.MAMH = k.MAMH
    )
    GROUP BY k.MAMH, h.MAHV, h.HO, h.TEN
) AS A
WHERE XepHang = 1;

