--QLBH
--cau12
SELECT SOHD
FROM CTHD
WHERE (MASP = 'BB01' OR MASP = 'BB02') AND (SL BETWEEN 10 AND 20)
--cau13
SELECT SOHD
FROM CTHD
WHERE MASP = 'BB01'
INTERSECT 
SELECT SOHD 
FROM CTHD
WHERE MASP = 'BB02'
-- Cau 14 

SELECT DISTINCT s.MASP, s.TENSP 
FROM SANPHAM s
JOIN CTHD c 
ON s.MASP = c.MASP 
WHERE s.NUOCSX = 'Trung Quoc' OR c.SOHD IN (
	SELECT SOHD
	FROM HOADON h 
	WHERE h.NGHD = '01/01/2007')

-- Cau 15 

SELECT s.MASP, s.TENSP
FROM SANPHAM s 
WHERE s.MASP NOT IN (
	SELECT DISTINCT c.MASP
	FROM CTHD c)
	
-- Cau 16 
	
SELECT s.MASP, s.TENSP 
FROM SANPHAM s
WHERE s.MASP NOT IN (
	SELECT c.MASP 
	FROM CTHD c
	JOIN HOADON h
	ON c.SOHD = h.SOHD
	WHERE YEAR(h.NGHD) = 2006)

-- Cau 17 

SELECT s.MASP, s.TENSP 
FROM SANPHAM s
WHERE s.NUOCSX = 'Trung Quoc' AND s.MASP NOT IN (
	SELECT c.MASP 
	FROM CTHD c
	JOIN HOADON h
	ON c.SOHD = h.SOHD
	WHERE YEAR(h.NGHD) = 2006)

-- Cau 18 
	
SELECT HD.SOHD
FROM HOADON HD
WHERE NOT EXISTS ( 
	SELECT * 
	FROM SANPHAM SP
	WHERE SP.NUOCSX = 'Singapore' AND NOT EXISTS (
		SELECT *	
		FROM CTHD
		WHERE CTHD.MASP = SP.MASP AND HD.SOHD = CTHD.SOHD 
	)
)
