--QLGV
-- Cau 1  


SELECT GIAOVIEN.HOTEN, GIAOVIEN.MAGV, GIAOVIEN.HESO, KHOA.TRGKHOA 
FROM GIAOVIEN 
JOIN KHOA 
ON GIAOVIEN.MAGV = KHOA.TRGKHOA

UPDATE GIAOVIEN 
SET HESO = HESO + 0.2 
FROM GIAOVIEN 
JOIN KHOA 
ON GIAOVIEN.MAGV = KHOA.TRGKHOA

-- Cau 2 
UPDATE HocVien
SET DiemTB = (
	SELECT AVG(Diem)
	FROM KetQuaThi
	WHERE LanThi = (SELECT MAX(LanThi) FROM KetQuaThi KQ WHERE MaHV = KetQuaThi.MaHV GROUP BY MaHV)
	GROUP BY MaHV
	HAVING MaHV = HocVien.MaHV
)

-- Cau 3 
SELECT * 
FROM HOCVIEN, KETQUATHI 
WHERE (KETQUATHI.LANTHI = 3 AND KETQUATHI.DIEM < 5 AND KETQUATHI.MAHV = HOCVIEN.MAHV)

UPDATE HOCVIEN 
SET GHICHU = 'Cam Thi' 
FROM HOCVIEN, KETQUATHI 
WHERE (KETQUATHI.LANTHI = 3 AND KETQUATHI.DIEM < 5 AND KETQUATHI.MAHV = HOCVIEN.MAHV)

ALTER TABLE HOCVIEN
ALTER COLUMN DIEMTB VARCHAR(10);  -- Chuyển DIEMTB thành kiểu chuỗi

-- Cau 4 
UPDATE HOCVIEN
SET XEPLOAI = (
    CASE
        WHEN CONVERT(FLOAT, DIEMTB) >= 9 THEN 'XS'
        WHEN CONVERT(FLOAT, DIEMTB) >= 8 THEN 'G'
        WHEN CONVERT(FLOAT, DIEMTB) >= 6.5 THEN 'K'
        WHEN CONVERT(FLOAT, DIEMTB) >= 5 THEN 'TB'
        ELSE 'Y'
    END
);



-- Cau 6 
SELECT DISTINCT MH.TENMH 
FROM MONHOC MH, GIANGDAY GD, GIAOVIEN GV 
WHERE MH.MAMH = GD.MAMH AND GV.MaGV = GD.MaGV AND GD.HOCKY = 1 AND GD.NAM = 2006 AND GV.HOTEN = 'Tran Tam Thanh'


-- Cau 7 
SELECT DISTINCT MH.MAMH, MH.TENMH
FROM MONHOC MH JOIN GIANGDAY GD
ON MH.MAMH = GD.MAMH
WHERE GD.HOCKY = 1
	AND GD.NAM = 2006
	AND GD.MAGV = (
	  	SELECT MAGV 
	  	FROM LOP 
	  	WHERE MALOP = 'K11'
	)

-- Cau 8 
SELECT HO + ' ' + TEN AS HOTEN 
FROM HOCVIEN HV JOIN LOP
ON HV.MAHV = LOP.TRGLOP
WHERE HV.MALOP = ( 
	SELECT GD.MALOP 
	FROM GIANGDAY GD
	JOIN GIAOVIEN GV 
	ON GD.MAGV = GV.MAGV 
	WHERE GD.MAMH = 'CSDL' AND GV.HOTEN = 'Nguyen To Lan'
)

-- Cau 9 
SELECT MAMH, TENMH
FROM MONHOC
WHERE MAMH IN (
	SELECT DK.MAMH_TRUOC
	FROM MONHOC MH JOIN DIEUKIEN DK
	ON MH.MAMH = DK.MAMH
	WHERE MH.TENMH = 'Co So Du Lieu'
)

-- Cau 10 
SELECT MH.MAMH, MH.TENMH
FROM MONHOC MH 
WHERE MH.MAMH IN (
	SELECT DK.MAMH
	FROM MONHOC MH JOIN DIEUKIEN DK
	ON MH.MAMH = DK.MAMH_TRUOC
	WHERE MH.TENMH = 'Cau truc roi rac'
)
-- Cau 11 
SELECT GV.HOTEN 
FROM GIAOVIEN GV
JOIN GIANGDAY GD
ON GV.MAGV = GD.MAGV
WHERE GD.MALOP = 'K11' AND GD.HOCKY = 1 AND GD.NAM = 2006
INTERSECT
(
    SELECT GV.HOTEN 
    FROM GIAOVIEN GV
    JOIN GIANGDAY GD
    ON GV.MAGV = GD.MAGV
    WHERE GD.MALOP = 'K12' AND GD.HOCKY = 1 AND GD.NAM = 2006
);


-- Cau 12 
SELECT DISTINCT HV.MAHV , HV.HO  + ' ' + HV.TEN AS HOTEN
FROM HOCVIEN HV
JOIN KETQUATHI KQ 
ON HV.MAHV = KQ.MAHV 
WHERE KQ.MAMH = 'CSDL' AND KQ.LANTHI = 1 AND KQ.KQUA = 'Khong Dat' AND NOT EXISTS (
	SELECT *
	FROM KETQUATHI KQ
	WHERE KQ.MAHV = HV.MAHV AND KQ.LANTHI > 1
)

-- Cau 13 
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV 
WHERE GV.MAGV NOT IN (
	SELECT MAGV
	FROM GIANGDAY
)

-- Cau 14 
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV 
WHERE NOT EXISTS (
	SELECT *
	FROM GIANGDAY GD
	JOIN MONHOC MH
	ON GD.MAMH = MH.MAMH 
	WHERE GD.MAGV = GD.MAGV AND MH.MAKHOA = GV.MAKHOA 
)

-- Cau 15 
SELECT DISTINCT HV.HO  + ' ' + HV.TEN AS HOTEN
FROM HOCVIEN HV
WHERE MALOP = 'K11' AND (
	EXISTS (
		SELECT *
		FROM KETQUATHI KQ
		WHERE LANTHI > 3 AND KQUA = 'Khong Dat' AND HV.MAHV = KQ.MAHV
	) OR EXISTS (
		SELECT *
		FROM KETQUATHI KQ
		WHERE KQ.MAMH = 'CTRR' AND KQ.LANTHI = 2 AND KQ.DIEM = 5 AND HV.MAHV = KQ.MAHV 
	)
)

-- Cau 16 
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN GIANGDAY GD
ON GV.MAGV = GD.MAGV
WHERE GD.MAMH = 'CTRR'		
GROUP BY HOTEN, HOCKY, NAM
HAVING COUNT(*) >= 2

-- Cau 17 
SELECT HV.* , KQ.DIEM AS 'DIEM THI CUOI CUNG'
FROM HOCVIEN HV JOIN KETQUATHI KQ
ON HV.MAHV = KQ.MAHV
WHERE KQ.MAMH = 'CSDL' AND LANTHI = ( 
	SELECT MAX(LANTHI)
	FROM KETQUATHI 
	WHERE HV.MAHV = KQ.MAHV AND KQ.MAMH = 'CSDL'
)

-- Cau 18 
SELECT HV.*, KQ.DIEM AS 'DIEM CAO NHAT'
FROM HOCVIEN HV JOIN KETQUATHI KQ
ON HV.MAHV = KQ.MAHV
WHERE KQ.MAMH = 'CSDL' AND KQ.DIEM = ( 
	SELECT MAX(DIEM) 
	FROM KETQUATHI
	WHERE KETQUATHI.MAHV = HV.MAHV AND KETQUATHI.MAMH = 'CSDL'
	GROUP BY MAHV
)